name: "TP-Link Action"
description: "This action controls TP-Link smart devices from GitHub workflows."
inputs:
  email:
    description: "Email address used to authenticate TP-Link account. You should use a secret to store this so it isn't visible."
    required: true
  password:
    description: "Password used to authenticate TP-Link account. You should use a secret to store this so it isn't visible."
    required: true
  deviceType:
    description: "Device type. e.g. 'HS100'"
    required: true
  deviceId:
    description: "Device id/alias."
    required: true
  operation:
    description: "Operation you want to perform on device e.g. 'powerOn'."
    required: true 
outputs:
  result:
    description: "The result of the TP-Link request."
runs:
  using: 'node12'
  main: 'index.js'
